# Funding - Support mendix-expert development
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# If you ever want to accept sponsorships:
# github: jordnlvr
# ko_fi: jordnlvr
# buy_me_a_coffee: jordnlvr

# For now, just encourage contributions
custom: ["https://github.com/jordnlvr/mendix-mcp-server/blob/main/CONTRIBUTING.md"]
